export const HORIZONTAL_MENU_CONSTANT = ["Home", "NBA", "NFL", "MLB", "NHL", "CBB", "CFB",
    "NASCAR", "GOLF", "VIDEO", "LIFESTYLE", "DEALBOOK", "TEST1", "TEST2", "TEST3", "TEST4", "TEST5", "TEST6",
    "TEST7", "TEST8", "TEST9", "TEST10", "TEST11", "TEST12", "TEST13"]